{"ob":[
{char:  "一",  names: [ "イチ" ], strokes: 1 },
{char:  "丶",  names: [ "てん" ], strokes: 1 },
{char:  "｜",  names: [ "ぼう","たてぼう" ], strokes: 1 },

{char:  "ノ",  names: [ "の","はらいぼう" ], strokes: 1 },
{char:  "乙",  names: [ "オツ", "おつにょう", "つりばり" ], strokes: 1 },
{char:  "亅",  names: [ "はねぼう", "ケツ", "かぎ" ], strokes: 1 },
{char:  "二",  names: [ "ニ" ], strokes: 2 },
{char:  "亠",  names: [ "けいさんかんむり", "なべぶた", "けさんかんむり" ], strokes: 2 },
{char:  "人",  names: [ "ひと", "にんべん", "ひとがしら", "ひとやね" ], strokes: 2 },
{char:  "儿",  names: [ "にんにょう", "ひとあし" ], strokes: 2 },
{char:  "入",  names: [ "いる", "いりがしら", "いりやね", "ニュウ" ], strokes: 2 },
{char:  "ハ",  names: [ "ハチ", "はちがしら" ], strokes: 2 },
{char:  "冂",  names: [ "けいがまえ", "まきがまえ", "どうがまえ", "えんがまえ" ], strokes: 2 },
{char:  "冖",  names: [ "わかんむり", "べきかんむり" ], strokes: 2 },
{char:  "冫",  names: [ "にすい" ], strokes: 2 },
{char:  "几",  names: [ "つくえ", "きにょう", "つくえきにょう", "かぜかんむり", "かぜがまえ" ], strokes: 2 },
{char:  "凵",  names: [ "かんにょう", "うけばこ" ], strokes: 2 },
{char:  "刀",  names: [ "かたな", "りっとう" ], strokes: 2 },
{char:  "力",  names: [ "ちから" ], strokes: 2 },
{char:  "勹",  names: [ "つつみがまえ" ], strokes: 2 },
{char:  "匕",  names: [ "ヒ", "さじ", "さじのひ" ], strokes: 2 },
{char:  "匚",  names: [ "はこがまえ" ], strokes: 2 },
{char:  "十",  names: [ "ジュウ" ], strokes: 2 },
{char:  "卜",  names: [ "ボク", "ぼくのと", "うらない" ], strokes: 2 },
{char:  "卩",  names: [ "ふしづくり", "まげわりふ", "わりふ" ], strokes: 2 },
{char:  "厂",  names: [ "がんだれ" ], strokes: 2 },
{char:  "厶",  names: [ "む" ], strokes: 2 },
{char:  "又",  names: [ "また" ], strokes: 2 },
{char:  "口",  names: [ "くち", "くちへん" ], strokes: 3 },
{char:  "⺾",  names: [ "くさ","くさかんむり","そうこう"], strokes: 3},
{char:  "囗",  names: [ "くにがまえ" ], strokes: 3 },
{char:  "⺹",  names: [ "おいる","おいかんむり","おいがしら" ], strokes: 3 },
{char:  "土",  names: [ "つち", "つちへん" ], strokes: 3 },
{char:  "士",  names: [ "さむらい", "さむらいかんむり" ], strokes: 3 },
{char:  "夂",  names: [ "ふゆがしら", "ちかんむり", "のまたかんむり" ], strokes: 3 },
{char:  "夕",  names: [ "ゆう", "ゆうべ", "タ" ], strokes: 3 },
{char:  "大",  names: [ "ダイ", "だいかんむり", "だいかしら" ], strokes: 3 },
{char:  "女",  names: [ "おんな", "おんなへん" ], strokes: 3 },
{char:  "子",  names: [ "こ", "こへん", "こども", "こどもへん" ], strokes: 3 },
{char:  "宀",  names: [ "うかんむり" ], strokes: 3 },
{char:  "寸",  names: [ "スン" ], strokes: 3 },
{char:  "小",  names: [ "ショウ", "ちいさい", "しょうがしら", "なおがしら" ], strokes: 3 },
{char:  "尢",  names: [ "だいのまげあし", "まげあし", "おうにょう", "オウ" ], strokes: 3 },
{char:  "尸",  names: [ "しかばね", "しかばねかんむり", "かばね", "かばねだれ" ], strokes: 3 },
{char:  "屮",  names: [ "テツ", "くさのめ", "めばえ" ], strokes: 3 },
{char:  "山",  names: [ "やま", "やまへん" ], strokes: 3 },
{char:  "巛",  names: [ "まがりかわ", "かわ", "さんぽがわ" ], strokes: 3 },
{char:  "川",  names: [ "まがりかわ", "かわ", "さんぽがわ" ], strokes: 3 },
{char:  "工",  names: [ "コウ", "たくみへん", "たくみ" ], strokes: 3 },
{char:  "巾",  names: [ "はば", "はばへん", "きんへん", "きんべん" ], strokes: 3 },
{char:  "干",  names: [ "カン", "いちじゅう", "ほす" ], strokes: 3 },
{char:  "ヨ",  names: [ "ヨウ", "もちいる" ], strokes: 5 },
{char:  "幺",  names: [ "ヨウ", "いとがしら" ], strokes: 3 },
{char:  "广",  names: [ "まだれ" ], strokes: 3 },
{char:  "廴",  names: [ "えんにょう", "えんにゅう", "いんにょう" ], strokes: 3 },
{char:  "廾",  names: [ "キョウ", "こまぬき", "にじゅうあし" ], strokes: 3 },
{char:  "弋",  names: [ "ヨク", "しきがまえ" ], strokes: 3 },
{char:  "弓",  names: [ "ゆみ", "ゆみへん" ], strokes: 3 },
{char:  "彑",  names: [ "けいがしら", "いのこがしら" ], strokes: 3 },
{char:  "彡",  names: [ "さんづくり", "けかざり", "かみかざり" ], strokes: 3 },
{char:  "彳",  names: [ "ぎょうにんべん" ], strokes: 3 },
{char:  "心",  names: [ "こころ", "りっしんべん", "したごころ" ], strokes: 4 },
{char:  "忄",  names: [ "こころ", "りっしんべん", "したごころ" ], strokes: 4 },
{char:  "戈",  names: [ "ほこ", "ほこづくり", "ほこがまえ", "たすき", "かのほこ" ], strokes: 4 },
{char:  "戸",  names: [ "と", "とかんむり", "とだれ", "とびらのと" ], strokes: 4 },
{char:  "手",  names: [ "て", "てへん" ], strokes: 4 },
{char:  "扌",  names: [ "て", "てへん" ], strokes: 4 },
{char:  "支",  names: [ "しにょう", "えだにょう", "じゅうまた" ], strokes: 4 },
{char:  "攵",  names: [ "ぼくづくり", "ぼくにょう", "のぶん", "しぶん", "とまた" ], strokes: 4 },
{char:  "文",  names: [ "ブン", "ぶんにょう", "ふみつくり" ], strokes: 4 },
{char:  "斗",  names: [ "とます", "ます", "ト" ], strokes: 4 },
{char:  "斤",  names: [ "おの", "おのづくり", "キン" ], strokes: 4 },
{char:  "方",  names: [ "ホウ", "ほうへん", "かたへん" ], strokes: 4 },
{char:  "无",  names: [ "なし", "ブ", "むにょう", "すでのつくり" ], strokes: 4 },
{char:  "日",  names: [ "ひ", "にち", "ひへん", "にちへん" ], strokes: 4 },
{char:  "曰",  names: [ "ひらび", "いわく" ], strokes: 4 },
{char:  "月",  names: [ "つき", "つきへん", "ふなづき" ], strokes: 4 },
{char:  "木",  names: [ "き", "きへん" ], strokes: 4 },
{char:  "欠",  names: [ "あくび", "かける" ], strokes: 4 },
{char:  "止",  names: [ "とめる", "とめへん" ], strokes: 4 },
{char:  "歹",  names: [ "ガツ", "がつへん", "かばねへん", "しにがまえ", "いちたへん" ], strokes: 4 },
{char:  "殳",  names: [ "ほこづくり", "ほこ", "るまた" ], strokes: 4 },
{char:  "毋",  names: [ "なかれ", "はは", "ははのかん" ], strokes: 4 },
{char:  "母",  names: [ "なかれ", "はは", "ははのかん" ], strokes: 4 },
{char:  "比",  names: [ "ヒ", "ならびひ", "くらべる" ], strokes: 4 },
{char:  "毛",  names: [ "け" ], strokes: 4 },
{char:  "氏",  names: [ "うじ" ], strokes: 4 },
{char:  "气",  names: [ "きがまえ" ], strokes: 4 },
{char:  "氵",  names: [ "みず", "さんずい", "したみず" ], strokes: 3 },
{char:  "水",  names: [ "みず", "さんずい", "したみず" ], strokes: 4 },
{char:  "灬",  names: [ "ひ", "ひへん", "れっか", "れんが" ], strokes: 4 },
{char:  "火",  names: [ "ひ", "ひへん", "れっか", "れんが" ], strokes: 4 },
{char:  "爪",  names: [ "つめ", "そうにょう", "つめかんむり" ], strokes: 4 },
{char:  "父",  names: [ "ちち" ], strokes: 4 },
{char:  "爻",  names: [ "コウ" ], strokes: 4 },
{char:  "爿",  names: [ "ショウ", "しょうへん" ], strokes: 4 },
{char:  "片",  names: [ "かた", "かたへん" ], strokes: 4 },
{char:  "牙",  names: [ "きば", "きばへん" ], strokes: 4 },
{char:  "犭",  names: [ "いぬ", "けものへん" ], strokes: 4 },
{char:  "牛",  names: [ "うし", "うしへん" ], strokes: 4 },
{char:  "犬",  names: [ "いぬ", "けものへん" ], strokes: 4 },
{char:  "玄",  names: [ "ゲン" ], strokes: 5 },
{char:  "王",  names: [ "たま", "たまへん", "おうへん" ], strokes: 5 },
{char:  "瓜",  names: [ "うり" ], strokes: 5 },
{char:  "瓦",  names: [ "かわら" ], strokes: 5 },
{char:  "甘",  names: [ "あまい", "カン" ], strokes: 5 },
{char:  "生",  names: [ "セイ", "ショウ", "いきる", "うまれる" ], strokes: 5 },
{char:  "用",  names: [ "ヨウ", "もちいる" ], strokes: 5 },
{char:  "田",  names: [ "た", "たへん" ], strokes: 5 },
{char:  "疋",  names: [ "ヒキ", "ひきへん" ], strokes: 5 },
{char:  "疒",  names: [ "やまいだれ" ], strokes: 5 },
{char:  "癶",  names: [ "はつがしら" ], strokes: 5 },
{char:  "白",  names: [ "しろ", "しろへん" ], strokes: 5 },
{char:  "皮",  names: [ "けがわ", "ひのかわ" ], strokes: 5 },
{char:  "皿",  names: [ "さら" ], strokes: 5 },
{char:  "目",  names: [ "め", "めへん", "よこめ" ], strokes: 5 },
{char:  "罒",  names: [ "め", "めへん", "よこめ" ], strokes: 5 },
{char:  "矛",  names: [ "ほこ", "ほこへん" ], strokes: 5 },
{char:  "矢",  names: [ "や", "やへん" ], strokes: 5 },
{char:  "石",  names: [ "いし", "いしへん" ], strokes: 5 },
{char:  "礻",  names: [ "しめす", "しめすへん", "ねへん" ], strokes: 4 },
{char:  "示",  names: [ "しめす", "しめすへん", "ねへん" ], strokes: 5 },
{char:  "禸",  names: [ "ぐうのあし" ], strokes: 5 },
{char:  "禾",  names: [ "いね", "いねへん", "のぎ", "のぎへん" ], strokes: 5 },
{char:  "穴",  names: [ "あな", "あなかんむり" ], strokes: 5 },
{char:  "立",  names: [ "たつ", "たつへん" ], strokes: 5 },
{char:  "竹",  names: [ "たけ", "たけかんむり" ], strokes: 6 },
{char:  "米",  names: [ "こめ", "こめへん" ], strokes: 6 },
{char:  "糸",  names: [ "いと", "いとへん" ], strokes: 6 },
{char:  "缶",  names: [ "ほとぎ", "ほとぎへん", "フ", "カン" ], strokes: 6 },
{char:  "羊",  names: [ "ひつじ", "ひつじへん" ], strokes: 6 },
{char:  "羽",  names: [ "はね" ], strokes: 6 },
{char:  "而",  names: [ "しこうして", "しかして" ], strokes: 6 },
{char:  "耒",  names: [ "らいすき", "すきへん" ], strokes: 6 },
{char:  "耳",  names: [ "みみ", "みみへん" ], strokes: 6 },
{char:  "聿",  names: [ "イツ", "ふでづくり" ], strokes: 6 },
{char:  "肉",  names: [ "ニク", "にくづき" ], strokes: 6 },
{char:  "臣",  names: [ "シン" ], strokes: 6 },
{char:  "自",  names: [ "ジ", "みずから" ], strokes: 6 },
{char:  "至",  names: [ "いたる", "いたるへん" ], strokes: 6 },
{char:  "臼",  names: [ "うす" ], strokes: 6 },
{char:  "舌",  names: [ "した", "したへん" ], strokes: 6 },
{char:  "舛",  names: [ "まいあし", "ます" ], strokes: 6 },
{char:  "舟",  names: [ "ふね", "ふねへん" ], strokes: 6 },
{char:  "艮",  names: [ "コン", "ゴン", "こんづくり", "ごんづくり", "ねづくり", "うしとら" ], strokes: 6 },
{char:  "色",  names: [ "いろ" ], strokes: 6 },
{char:  "虍",  names: [ "とらかんむり", "とらがしら" ], strokes: 6 },
{char:  "虫",  names: [ "むし", "むしへん" ], strokes: 6 },
{char:  "血",  names: [ "ち" ], strokes: 6 },
{char:  "行",  names: [ "ゆきがまえ", "ぎょうがまえ" ], strokes: 6 },
{char:  "衣",  names: [ "ころも", "ころもへん" ], strokes: 6 },
{char:  "衤",  names: [ "ころも", "ころもへん" ], strokes: 5 },
{char:  "西",  names: [ "おおいかんむり", "にし" ], strokes: 6 },
{char:  "見",  names: [ "みる" ], strokes: 7 },
{char:  "角",  names: [ "つの", "つのへん" ], strokes: 7 },
{char:  "言",  names: [ "ことば", "ゲン", "ごんべん" ], strokes: 7 },
{char:  "谷",  names: [ "たに", "たにへん" ], strokes: 7 },
{char:  "豆",  names: [ "まめ", "まめへん" ], strokes: 7 },
{char:  "豕",  names: [ "いのこ", "いのこへん", "ぶた" ], strokes: 7 },
{char:  "豸",  names: [ "むじなへん" ], strokes: 7 },
{char:  "貝",  names: [ "かい", "かいへん", "こがい" ], strokes: 7 },
{char:  "赤",  names: [ "あか", "あかへん" ], strokes: 7 },
{char:  "走",  names: [ "はしる", "そうにょう" ], strokes: 7 },
{char:  "足",  names: [ "あし", "あしへん" ], strokes: 7 },
{char:  "身",  names: [ "み", "みへん" ], strokes: 7 },
{char:  "車",  names: [ "くるま", "くるまへん" ], strokes: 7 },
{char:  "辛",  names: [ "シン", "からい" ], strokes: 7 },
{char:  "辰",  names: [ "しんのたつ" ], strokes: 7 },
{char:  "⻏",  names: [ "むら", "おおざと" ], strokes: 7 },
{char:  "酉",  names: [ "とりへん", "ひよみのとり", "さけのとり", "とり" ], strokes: 7 },
{char:  "釆",  names: [ "のごめ", "のごめへん" ], strokes: 7 },
{char:  "里",  names: [ "さと", "さとへん" ], strokes: 7 },
{char:  "金",  names: [ "かね", "かねへん" ], strokes: 8 },
{char:  "長",  names: [ "ながい" ], strokes: 8 },
{char:  "門",  names: [ "モン", "もんがまえ", "かどがまえ" ], strokes: 8 },
{char:  "隶",  names: [ "れいづくり" ], strokes: 8 },
{char:  "隹",  names: [ "ふるとり" ], strokes: 8 },
{char:  "雨",  names: [ "あめ", "あめかんむり" ], strokes: 8 },
{char:  "青",  names: [ "あお" ], strokes: 8 },
{char:  "非",  names: [ "あらず", "ヒ" ], strokes: 8 },
{char:  "面",  names: [ "メン" ], strokes: 9 },
{char:  "革",  names: [ "かわへん", "つくりがわ" ], strokes: 9 },
{char:  "韋",  names: [ "なめしがわ" ], strokes: 9 },
{char:  "韭",  names: [ "にら" ], strokes: 9 },
{char:  "音",  names: [ "おと", "おとへん" ], strokes: 9 },
{char:  "頁",  names: [ "おおがい" ], strokes: 9 },
{char:  "風",  names: [ "かぜ" ], strokes: 9 },
{char:  "飛",  names: [ "とぶ" ], strokes: 9 },
{char:  "食",  names: [ "ショク", "しょくへん" ], strokes: 9 },
{char:  "首",  names: [ "くび" ], strokes: 9 },
{char:  "香",  names: [ "かおり", "カ" ], strokes: 9 },
{char:  "馬",  names: [ "うま", "うまへん" ], strokes: 10 },
{char:  "骨",  names: [ "ほね", "ほねへん" ], strokes: 10 },
{char:  "高",  names: [ "たかい" ], strokes: 10 },
{char:  "髟",  names: [ "かみかんむり", "かみがしら" ], strokes: 10 },
{char:  "鬥",  names: [ "とうがまえ", "たたかいがまえ" ], strokes: 10 },
{char:  "鬯",  names: [ "チョウ", "においざけ" ], strokes: 10 },
{char:  "鬲",  names: [ "かなえ", "レキ" ], strokes: 10 },
{char:  "鬼",  names: [ "おに", "きにょう" ], strokes: 10 },
{char:  "魚",  names: [ "うお", "さかな", "うおへん" ], strokes: 11 },
{char:  "鳥",  names: [ "とり", "とりへん" ], strokes: 11 },
{char:  "鹵",  names: [ "しお", "ロ" ], strokes: 11 },
{char:  "鹿",  names: [ "しか" ], strokes: 11 },
{char:  "麦",  names: [ "むぎ", "ばくにょう" ], strokes: 11 },
{char:  "麻",  names: [ "あさ", "あさかんむり" ], strokes: 11 },
{char:  "黄",  names: [ "き" ], strokes: 12 },
{char:  "黍",  names: [ "きび" ], strokes: 12 },
{char:  "黒",  names: [ "くろ" ], strokes: 12 },
{char:  "黹",  names: [ "ぬいとり", "ふつへん", "チ" ], strokes: 12 },
{char:  "黽",  names: [ "べんあし", "かえる", "ベン" ], strokes: 13 },
{char:  "鼎",  names: [ "かなえ", "テイ" ], strokes: 13 },
{char:  "鼓",  names: [ "つづみ" ], strokes: 13 },
{char:  "鼠",  names: [ "ねずみ", "ねずみへん" ], strokes: 13 },
{char:  "鼻",  names: [ "はな", "はなへん" ], strokes: 14 },
{char:  "斉",  names: [ "セイ" ], strokes: 8 },
{char:  "歯",  names: [ "は", "はへん" ], strokes: 15 },
{char:  "竜",  names: [ "りゅう" ], strokes: 10 },
{char:  "亀",  names: [ "かめ" ], strokes: 16 },
{char:  "龠",  names: [ "ヤク", "ふえ" ], strokes: 17 },
]}
